import { KeyboardEvent, useEffect, useRef, useState } from 'react';
import { Brain, ChevronDown, Lightbulb, Paperclip, Plus, SendHorizontal, Sparkles, Zap } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { WorkspaceBottomMenu, WorkspaceSidebar } from './workspace-navigation';

export type WorkspaceMessage = { id: string; role: 'user' | 'assistant'; content: string; meta?: string };
const models = [{ id: 'balanced', name: 'Balanced', icon: Sparkles, color: 'text-brand' }, { id: 'fast', name: 'Fast', icon: Zap, color: 'text-amber-300' }, { id: 'deep', name: 'Deep reasoning', icon: Brain, color: 'text-cyan-300' }];

export function BoltStyleChat({ username, messages, isWorking, onSend }: { username?: string; messages: WorkspaceMessage[]; isWorking: boolean; onSend: (message: string) => void }) {
  const [input, setInput] = useState(''); const [model, setModel] = useState(models[0]); const [modelOpen, setModelOpen] = useState(false); const [sidebarOpen, setSidebarOpen] = useState(false); const [bottomMenuOpen, setBottomMenuOpen] = useState(false); const [notice, setNotice] = useState<string | null>(null); const textarea = useRef<HTMLTextAreaElement>(null); const end = useRef<HTMLDivElement>(null); const hasMessages = messages.length > 0; const ModelIcon = model.icon;
  useEffect(() => { end.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, isWorking]);
  useEffect(() => { if (textarea.current) { textarea.current.style.height = 'auto'; textarea.current.style.height = `${Math.min(textarea.current.scrollHeight, 180)}px`; } }, [input]);
  const submit = () => { if (!input.trim() || isWorking) return; onSend(input.trim()); setInput(''); }; const keyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }; const toggleSidebar = () => { setSidebarOpen((open) => !open); setBottomMenuOpen(false); }; const toggleBottom = () => { setBottomMenuOpen((open) => !open); setSidebarOpen(false); }; const handleNavigation = (label: string) => { if (label === 'New task') { setInput(''); textarea.current?.focus(); setNotice('Ready for a new task.'); } else if (label === 'Workspace') { setNotice('You are already in your workspace.'); } else { setNotice(`${label} is coming soon.`); } window.setTimeout(() => setNotice(null), 2600); };
  return <div className="relative flex min-h-screen flex-col overflow-hidden bg-[#0f0f12] text-white"><WorkspaceSidebar open={sidebarOpen} onToggle={toggleSidebar} onAction={handleNavigation} username={username} /><div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute left-1/2 top-[-35rem] size-[72rem] -translate-x-1/2 rounded-full border-[40px] border-brand/20 shadow-[0_0_140px_35px_rgba(108,59,255,0.2)]" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgba(108,59,255,0.16),transparent_34%)]" /></div>
    <header className={`relative z-10 flex items-center justify-between border-b border-white/[0.07] px-5 py-4 transition-[margin] sm:px-8 md:ml-14 ${sidebarOpen ? 'md:ml-56' : ''}`}><div className="flex items-center gap-2.5"><span className="grid size-8 place-items-center rounded-lg bg-brand text-sm font-black">a</span><span className="font-semibold tracking-tight">agēntīq</span></div><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-xs text-[#a0a0a8]">Autonomous workspace</span></header>
    <main className={`relative z-10 mx-auto flex w-full max-w-4xl flex-1 flex-col px-5 transition-[margin] md:ml-14 ${sidebarOpen ? 'md:ml-56' : ''} ${hasMessages ? 'pt-8 pb-36' : 'justify-center pb-28'}`}>{!hasMessages && <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mb-8 text-center"><div className="mx-auto mb-5 grid size-12 place-items-center rounded-2xl border border-brand/30 bg-brand/10 text-brand"><Sparkles className="size-6" /></div><h1 className="text-3xl font-bold tracking-tight sm:text-5xl">What would you like to <span className="bg-gradient-to-r from-brand via-[#a989ff] to-accent bg-clip-text text-transparent">get done?</span></h1><p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-[#a0a0a8] sm:text-base">Describe the outcome. agēntīq will select the right specialist, prepare the capabilities it needs, and begin the work.</p>{username && <p className="mt-4 text-xs font-medium text-brand">Ready when you are, @{username}</p>}</motion.div>}{hasMessages && <div className="mx-auto w-full max-w-3xl space-y-5">{messages.map((message) => <motion.article key={message.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${message.role === 'user' ? 'bg-brand text-white' : 'border border-white/[0.08] bg-white/[0.045] text-[#e8e8ec]'}`}><p className="whitespace-pre-wrap">{message.content}</p>{message.meta && <p className="mt-2 border-t border-white/10 pt-2 text-[11px] font-medium text-accent">{message.meta}</p>}</div></motion.article>)}{isWorking && <div className="flex items-center gap-2 text-sm text-[#a0a0a8]"><span className="size-2 animate-pulse rounded-full bg-accent" />Preparing the right agent and tools…</div>}<div ref={end} /></div>}</main>
    <div className={`fixed inset-x-0 bottom-0 z-20 bg-gradient-to-t from-[#0f0f12] via-[#0f0f12] to-transparent px-5 pb-5 pt-12 transition-[left] md:left-14 ${sidebarOpen ? 'md:left-56' : ''}`}><div className="mx-auto w-full max-w-3xl"><AnimatePresence>{notice && <motion.div role="status" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 6 }} className="mb-2 w-fit rounded-lg border border-white/10 bg-[#222229] px-3 py-2 text-xs text-[#c7c7cf] shadow-xl">{notice}</motion.div>}</AnimatePresence><div className="rounded-2xl border border-white/[0.1] bg-[#1a1a20] shadow-[0_12px_40px_rgba(0,0,0,0.4)]"><textarea ref={textarea} value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={keyDown} placeholder="Describe a task, goal, or problem…" className="min-h-[78px] w-full resize-none bg-transparent px-5 pb-3 pt-4 text-[15px] text-white outline-none placeholder:text-[#686870]" /><div className="flex items-center justify-between px-3 pb-3"><div className="flex items-center gap-1"><button type="button" title="Attachments coming soon" className="grid size-8 place-items-center rounded-full bg-white/[0.07] text-[#9898a1] hover:bg-white/10 hover:text-white"><Plus className="size-4" /></button><button type="button" title="Attachments coming soon" className="grid size-8 place-items-center rounded-full text-[#9898a1] hover:bg-white/[0.07] hover:text-white"><Paperclip className="size-4" /></button><div className="relative"><button type="button" onClick={() => setModelOpen(!modelOpen)} className="flex items-center gap-1 rounded-full px-2 py-1.5 text-xs text-[#aaaab2] hover:bg-white/[0.07] hover:text-white"><ModelIcon className={`size-3.5 ${model.color}`} />{model.name}<ChevronDown className="size-3" /></button>{modelOpen && <div className="absolute bottom-full left-0 mb-2 w-44 rounded-xl border border-white/10 bg-[#222229] p-1 shadow-2xl">{models.map((item) => { const Icon = item.icon; return <button key={item.id} type="button" onClick={() => { setModel(item); setModelOpen(false); }} className="flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-xs text-[#b7b7bf] hover:bg-white/[0.07] hover:text-white"><Icon className={`size-3.5 ${item.color}`} />{item.name}</button>; })}</div>}</div></div><div className="flex items-center gap-2"><span className="hidden text-xs text-[#777780] sm:inline"><Lightbulb className="mr-1 inline size-3.5" />Agent selected automatically</span><button onClick={submit} disabled={!input.trim() || isWorking} className="inline-flex items-center gap-2 rounded-xl bg-brand px-3.5 py-2 text-sm font-semibold hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40">Send<SendHorizontal className="size-4" /></button></div></div></div></div></div><WorkspaceBottomMenu open={bottomMenuOpen} onToggle={toggleBottom} onAction={handleNavigation} /></div>;
}
