import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Activity, Bot, ChevronLeft, ChevronRight, Clock3, Menu, MessageSquareText, Plus, Settings, Sparkles, type LucideIcon } from 'lucide-react';

type NavAction = (label: string) => void;
const navItems: Array<{ label: string; icon: LucideIcon; active?: boolean }> = [
  { label: 'New task', icon: Plus }, { label: 'Workspace', icon: MessageSquareText, active: true }, { label: 'Activity', icon: Activity }, { label: 'Agents', icon: Bot }, { label: 'History', icon: Clock3 },
];

export function WorkspaceSidebar({ open, onToggle, onAction, username }: { open: boolean; onToggle: () => void; onAction: NavAction; username?: string }) {
  return <motion.aside aria-label="Workspace navigation" animate={{ width: open ? 224 : 56 }} transition={{ type: 'spring', stiffness: 340, damping: 32 }} className="fixed inset-y-0 left-0 z-40 hidden border-r border-white/[0.08] bg-[#121217]/95 backdrop-blur-xl md:flex md:flex-col">
    <div className="flex h-16 items-center border-b border-white/[0.07] px-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-brand text-sm font-black">a</span><AnimatePresence initial={false}>{open && <motion.span initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -8 }} className="ml-2 truncate text-sm font-semibold">agēntīq</motion.span>}</AnimatePresence><button onClick={onToggle} aria-label={open ? 'Collapse sidebar' : 'Expand sidebar'} className="ml-auto grid size-7 shrink-0 place-items-center rounded-md text-midGray hover:bg-white/[0.07] hover:text-white">{open ? <ChevronLeft className="size-4" /> : <ChevronRight className="size-4" />}</button></div>
    <nav className="flex flex-1 flex-col gap-1 p-2">{navItems.map(({ label, icon: Icon, active }) => <button key={label} onClick={() => onAction(label)} title={label} className={`flex h-9 items-center rounded-lg px-2 text-left text-sm transition-colors ${active ? 'bg-brand/15 text-white' : 'text-midGray hover:bg-white/[0.06] hover:text-white'}`}><Icon className={`size-4 shrink-0 ${active ? 'text-brand' : ''}`} /><AnimatePresence initial={false}>{open && <motion.span initial={{ opacity: 0, x: -7 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -7 }} className="ml-3 whitespace-nowrap">{label}</motion.span>}</AnimatePresence></button>)}</nav>
    <div className="border-t border-white/[0.07] p-2"><button onClick={() => onAction('Settings')} title="Settings" className="flex h-9 w-full items-center rounded-lg px-2 text-midGray hover:bg-white/[0.06] hover:text-white"><Settings className="size-4 shrink-0" /><AnimatePresence initial={false}>{open && <motion.span initial={{ opacity: 0, x: -7 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -7 }} className="ml-3 whitespace-nowrap text-sm">Settings</motion.span>}</AnimatePresence></button><button onClick={() => onAction('Profile')} title="Profile" className="mt-2 flex w-full items-center px-2 text-left"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-accent/15 text-[10px] font-bold text-accent">{username?.slice(0, 2).toUpperCase() || 'AI'}</span><AnimatePresence initial={false}>{open && <motion.span initial={{ opacity: 0, x: -7 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -7 }} className="ml-2 truncate text-xs text-midGray">@{username || 'workspace'}</motion.span>}</AnimatePresence></button></div>
  </motion.aside>;
}

export function WorkspaceBottomMenu({ open, onToggle, onAction }: { open: boolean; onToggle: () => void; onAction: NavAction }) {
  const [hovered, setHovered] = useState<string | null>(null);
  const quickItems = [{ label: 'New task', icon: Plus }, { label: 'Workspace', icon: MessageSquareText }, { label: 'Agents', icon: Bot }, { label: 'Activity', icon: Activity }];
  return <motion.div aria-label="Quick workspace menu" animate={{ width: open ? 270 : 48 }} transition={{ type: 'spring', stiffness: 340, damping: 32 }} className="fixed bottom-5 right-5 z-30 hidden rounded-full border border-white/[0.1] bg-[#1a1a20]/95 p-1 shadow-2xl shadow-black/40 backdrop-blur-xl sm:block"><div className="relative flex h-9 items-center gap-1"><button onClick={onToggle} onMouseEnter={() => setHovered(open ? 'Collapse quick menu' : 'Expand quick menu')} onMouseLeave={() => setHovered(null)} aria-label={open ? 'Collapse quick menu' : 'Expand quick menu'} className="grid size-9 shrink-0 place-items-center rounded-full text-[#a0a0a8] hover:bg-white/[0.08] hover:text-white"><Menu className="size-4" /></button><AnimatePresence initial={false}>{open && <motion.div initial={{ opacity: 0, width: 0 }} animate={{ opacity: 1, width: 'auto' }} exit={{ opacity: 0, width: 0 }} className="flex items-center gap-1 overflow-hidden">{quickItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => onAction(label)} onMouseEnter={() => setHovered(label)} onMouseLeave={() => setHovered(null)} aria-label={label} className="grid size-9 shrink-0 place-items-center rounded-full text-[#a0a0a8] hover:bg-white/[0.08] hover:text-white"><Icon className="size-4" /></button>)}<span className="mx-1 h-4 w-px bg-white/10" /><button onClick={() => onAction('Tips')} onMouseEnter={() => setHovered('Tips')} onMouseLeave={() => setHovered(null)} aria-label="Tips" className="grid size-9 shrink-0 place-items-center rounded-full text-brand hover:bg-brand/15"><Sparkles className="size-4" /></button></motion.div>}</AnimatePresence><AnimatePresence>{hovered && <motion.span initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 4 }} className="pointer-events-none absolute bottom-full right-0 mb-2 whitespace-nowrap rounded-md border border-white/10 bg-[#222229] px-2 py-1 text-[11px] text-white shadow-lg">{hovered}</motion.span>}</AnimatePresence></div></motion.div>;
}
